# Generated by Django 5.0.2 on 2024-03-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
    ]
