# Generated by Django 5.0.2 on 2024-03-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_order_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='dateofbirth',
        ),
    ]
