# Generated by Django 5.0.2 on 2024-03-26 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_date_order_dateofbirth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='firstname',
            new_name='price',
        ),
    ]
